### ISSUE TITLE
pw-top Not Added To Build

### ISSUE THREAD

**Issue by jasker5183** [mkfrey/pipewire-nightly-copr#1]
````
pw-top
bash: pw-top: command not found...
````
Does it just need to be added to spec file?

**Comment by mkfrey** [comment]
Thanks for noticing me. I think this might need additional dependencies for building (ncurses-devel) and installation (ncurses-libs). I will look into it.

**Comment by mkfrey** [comment]
The pw-top tool was added to the spec file and a newly build package is already available on COPR.
