### ISSUE TITLE
Build will fail because of new pipewire-media-session service

### ISSUE THREAD

**Issue by pgbross** [mkfrey/pipewire-nightly-copr#10]
Pipewire added [systemd: add unit files for pipewire-media-session
](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/012a68f8ef33705f1a40ec8ac294b8cce7f6aa88) in one of today's commits.

See pull-request #9 for an updates spec with the added entries.

**Comment by mkfrey** [comment]
Thanks for the notification!
