### ISSUE TITLE
Build fails due to meson using new "feature" options

### ISSUE THREAD

**Issue by pgbross** [mkfrey/pipewire-nightly-copr#13]
Pipewire commit [meson: Use `feature` options everywhere it makes sense](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/485bae5eb00c0f5d3d91bd8bf1b302896571f4ed) changes meson options.

See pull-request #12 for  spec file with the updated meson options.

**Comment by mkfrey** [comment]
Thanks for the PR!
