### ISSUE TITLE
Some Bluetooth codecs have been disabled

### ISSUE THREAD

**Issue by dal00** [mkfrey/pipewire-nightly-copr#19]
Is there a reason to why some codecs are disabled in the builds?

APTX and AAC here: https://github.com/mkfrey/pipewire-nightly-copr/blob/37686e1caccb8ffcdc1c72bfc837360c473a94cc/pipewire.spec#L213

Could we get it re enabled?

**Comment by mkfrey** [comment]
aptX requires libopenaptx, which is not available in Fedora repositories due to possible patent and licensing issues. It's currently also not available in RPMFusion.

See here for some discussion on the topic: https://bugzilla.redhat.com/show_bug.cgi?id=1908922

**Comment by dal00** [comment]
What about aac?

On 2 April 2021 16:00:37 CEST, Markus Frey ***@***.***> wrote:
>aptX requires libopenaptx, which is not available in Fedora repositories due to possible patent and licensing issues. It's currently also not available in RPMFusion.
>
>See here for some discussion on the topic: https://bugzilla.redhat.com/show_bug.cgi?id=1908922
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mkfrey/pipewire-nightly-copr/issues/19#issuecomment-812543150
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mkfrey** [comment]
I'm looking into it. Seems doable.

**Comment by mkfrey** [comment]
I don't really know why it was disabled in the first place, but I enabled AAC and it should work after the next build.

**Comment by dal00** [comment]
Great, thanks! This should simplify some user testing!

On 2 April 2021 17:02:08 CEST, Markus Frey ***@***.***> wrote:
>I don't really know why it was disabled in the first place, but I enabled AAC and it should work after the next build.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mkfrey/pipewire-nightly-copr/issues/19#issuecomment-812568160
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
