### ISSUE TITLE
media-session.conf

### ISSUE THREAD

**Issue by jasker5183** [mkfrey/pipewire-nightly-copr#2]
New configuration file.

https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/24c68b00677dac8accd9eb929dad2efc76520ebb

**Comment by jasker5183** [comment]
False alarm.

**Comment by mkfrey** [comment]
Why false alarm? I fixed this isse after you reported it.

**Comment by jasker5183** [comment]
Oh I saw the build was late but once I saw the media-session.conf in there I thought I had filed this in error.
