### ISSUE TITLE
Build fails due to new libpulse dependency and filter-chain configs

### ISSUE THREAD

**Issue by pgbross** [mkfrey/pipewire-nightly-copr#21]
Pipewire commit [module-pulse-tunner](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/44f326013b5f5e1e858ee3788fe664f802ca2523) adds depdendency on libpulse.
`filter-chain` added recently adds new config directory `/etc/pipewire/filter-chain/` and corresponding files.

These changes require update to spec file to get the build working again.  See PR #20 for spec file updates.

**Comment by mkfrey** [comment]
Thanks for reporting and the PRs!
