### ISSUE TITLE
Build fails due to inclusion of optional wireplumber

### ISSUE THREAD

**Issue by pgbross** [mkfrey/pipewire-nightly-copr#25]
The wireplumber optional session manager is now included in the pipewire upstream repository (as a meson subproject) and that causes the build to fail as by default meson doesn't download from the .wrap files in subprojects.

The quick fix is to add `-D wireplumber=disabled` to the meson build options. (see PR #24)

It would be nice to support having the wireplumber in the build, but I haven't got that to work.

For that one needs to add some sources and requires:

```
Source1:	https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/master/wireplumber-master.tar.gz
Source2:  https://www.lua.org/ftp/lua-5.3.6.tar.gz
Source3:  https://wrapdb.mesonbuild.com/v1/projects/lua/5.3.6/1/get_zip
```

```
BuildRequires: python-sphinx
BuildRequires: python-sphinx_rtd_theme
BuildRequires: python-breathe
BuildRequires: python3-lxml
BuildRequires: gobject-introspection-devel
```

and modify the `%prep stage`
```
%prep
%setup -q -T -b0 -n %{name}-master
%setup -T -D -a 1 -n %{name}-master
%setup -T -D -a 2 -n %{name}-master
%setup -T -D -a 3 -n %{name}-master

mv wireplumber-master subprojects/wireplumber
mv lua-5.3.6 subprojects/lua
```

this is very close to working but in a test build this fails after about 4mins during testing with a "folder not found" error.

I have run out of time to look into why the wireplumber fails but have the PR for the simple fix that just excludes it for now.

**Comment by mkfrey** [comment]
Thanks for the information and the PR.

Do the last builds of the nightly repo work on your system? They are not working for me, but I cant figure out why. The spec is very close to upstream, the only difference being SDL2.

**Comment by pgbross** [comment]
So far I have always built `pipewire` in my own `copr` repository (as a test bed to ensure that the .spec file works before producing any PRs). Having said that, during my investigations about how to get `wireplumber` optional build to complete in the `copr` environment, I did build it locally. I will check `pipewire` locally from the current master and see what happens.
