### ISSUE TITLE
Build fails due to bluez5 libusb dependency

### ISSUE THREAD

**Issue by pgbross** [mkfrey/pipewire-nightly-copr#27]
Upstream [bluez5: backend-native: use quirks + usb adapter caps for checking msbc](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/5e0b63b149559154a6164dbc064aefc7e773c03a) adds libusb dependency.

see PR #26 for fix.

**Comment by mkfrey** [comment]
Thanks for the PR!
