### ISSUE TITLE
Build fails due to meson options looking for roc streaming

### ISSUE THREAD

**Issue by pgbross** [mkfrey/pipewire-nightly-copr#29]
Commit [meson: adds post meson setup/--reconfigure summary for auto features](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/71d39e90ed6bd8729f6ae0ab8d1bf5d2640bc3df) changes meson options handling to use roc streaming. This fails as the roc streaming toolkit is not available.

Add `-D roc=disabled` see PR #28

**Comment by mkfrey** [comment]
Thanks, as always.
