### ISSUE TITLE
New config files 

### ISSUE THREAD

**Issue by jasker5183** [mkfrey/pipewire-nightly-copr#3]
If your having some problems with the build it may be because of the new config files bluez-monitor.conf and v4l2-monitor.conf.

https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/fee0c2679ccffb6b57c0858256d63e0b91fa35ec

**Comment by mkfrey** [comment]
The files have been added to the spec file and will be included in the next build. Thanks for reporting.
