### ISSUE TITLE
Build fails due to jack-devel changing to a boolean

### ISSUE THREAD

**Issue by pgbross** [mkfrey/pipewire-nightly-copr#31]
Build fails due to [[Meson] Change jack-devel option to be boolean](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/a5e3d3f7a78b3305da9632cd96a1af22f02a5293) comit.

Fix in PR #30

**Comment by mkfrey** [comment]
Thanks! I thought the build issue was still caused by an outdated meson version.
