### ISSUE TITLE
Build fails due to moved bluez-hardware.conf and new ps_dsdplay tool

### ISSUE THREAD

**Issue by pgbross** [mkfrey/pipewire-nightly-copr#33]
Build fails due to moved  [bluez5: move bluez-hardware.conf loading to the plugin](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/cae15544494acaa5732945aa56c7a191c6f94b92)

and also reference new pw_dsdplay.

I notice that there are already new commits to move pw-dsdplay into pw-cat, so may need to tweak the PR to remove the reference to pw-dsdplay.

see PR #32

**Comment by mkfrey** [comment]
Thanks as always!
