### ISSUE TITLE
0.3.21-2 Is Superceding the Nightly

### ISSUE THREAD

**Issue by jasker5183** [mkfrey/pipewire-nightly-copr#4]
Tried updating tonight and it wants to install 0.3.21-2 rather than the nightly going to have to go manual.

**Comment by mkfrey** [comment]
Looks like I've been missing the new release version. I will update the repo accordingly.

**Comment by mkfrey** [comment]
The repo has been updated. Nightly should supersede the official version after the next build. Thanks for reporting!
