### ISSUE TITLE
Build fails due to openssl dependency in new RAOP capability

### ISSUE THREAD

**Issue by pgbross** [mkfrey/pipewire-nightly-copr#41]
Build fails due to openssl dependency in new RAOP capability [add beginnings of RAOP protocol](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/9223fc2885e65cab6faba4f671cef3eed78f34d4).

see #40

**Comment by mkfrey** [comment]
Merged. Thanks, as always.
