### ISSUE TITLE
Build fails due to libcanberra and libX11-xcb dependency

### ISSUE THREAD

**Issue by pgbross** [mkfrey/pipewire-nightly-copr#46]
Build fails due to libcanberra and libX11-xcb dependency in support for  [X11-bell module](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/0cd0ef59128c7f9ac81182d3ab7348ddbe721259).

see #45

Note the Fedora 35 build will still fail due to bug #44, but it fixes Fedora 34 (hopefully Fedora 35 will start working when a fix is made upstream).

**Comment by mkfrey** [comment]
Thanks for the PR! What setup do you use to test the builds?

**Comment by pgbross** [comment]
I have a clone of your COPR repository and in the rebuild I just use the name of the branch I am testing as the "commitish". Generally for simple new dependencies it is straightforward, but occasionally as with the Fedora 35 issue it takes a few goes testing possibilities. 

For good measure I usually also look at the Fedora rawhide version of the SPEC file in case they have already committed a fix.

**Comment by mkfrey** [comment]
So you also use the COPR servers for your builds?

**Comment by pgbross** [comment]
Yes, but just to test my potential fixes against a clone of your repo (you can see my fork in the list of forks against your COPR).

**Comment by mkfrey** [comment]
Thanks for your answers. I was just interested because I tried to build locally for faster results, but it's way more complicated than the simple `copr-cli buildscm` command, and maybe you had a solution to this.
