### ISSUE TITLE
Build fails due to libspa-aec and libspa-webrtc dynamic libraries requirement

### ISSUE THREAD

**Issue by pgbross** [mkfrey/pipewire-nightly-copr#48]
Build fails due to libspa-aec and libspa-webrtc dynamic libraries requirement in [module-echo-cancel: Move backends to dynamic libaries
](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/9386c70b3a2cc2df6aabfd7b6a6bc1d7ec873bd1)

see #47

**Comment by mkfrey** [comment]
Thanks!
