### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by jasker5183** [mkfrey/pipewire-nightly-copr#5]
Builds been failing for the last two days it might be <https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/210400438290faa59790ca30926ac22e1dedb4b6>. Not too sure.

**Comment by jasker5183** [comment]
Also which, I'm sure would break the build tonight, there is a new config file client.conf. <https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/c605672d434484ccdcc5b3b802ddfb6c123eecad>

**Comment by mkfrey** [comment]
Thanks, I've added the two new config files `client.conf` and `pipewire-pulse.conf`.

**Comment by mkfrey** [comment]
The build still seems to fail because of a missing vulkan dependency. I have to take a look at it.

**Comment by pgbross** [comment]
In addition there are two new files in /etc/pipewire that need adding to the files section:

They are `/etc/pipewire/client-rt.conf` and `/etc/pipewire/jack.conf` otherwise it fails in the check section.

**Comment by pgbross** [comment]
Ok so yesterday `spa-json-dump` tool was added to PipeWire. This means the spec also needs it adding to the list of utils files (around line 358):

```
%{_bindir}/spa-json-dump
```

**Comment by mkfrey** [comment]
@pgbross Thanks for the information. Do you think jack.conf and pipewire-pulse.conf belong to the jack and pulse packages or into the core pipewire package?

**Comment by pgbross** [comment]
@mkfrey I looked at the sources as well and did a search across all the repository files and they aren't referenced anywhere else, so I think putting them in the `%files` for their respective packages is right.
